[project]
name = "n8n-mcp-client"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pytelegrambotapi>=4.28.0",
    "python-dotenv>=1.1.1",
    "pytz>=2025.2",
]

[tool.uv]
